from dea.bulk.eml import eml

activity_cdo_id = "46"

institution_cdo_id = "45"

activity_import_def = {
    "Meeting_Type": "{{CustomObject[46].Field[587]}}",
    "Meeting_SubType": "{{CustomObject[46].Field[588]}}",
    "Meeting_ID": "{{CustomObject[46].Field[585]}}",
    "Start_Time": "{{CustomObject[46].Field[589]}}",
    "End_time": "{{CustomObject[46].Field[590]}}",
    "Duration": "{{CustomObject[46].Field[591]}}",
    "Accomplished": "{{CustomObject[46].Field[592]}}",
    "Meeting_Place": "{{CustomObject[46].Field[593]}}",
    "IM_CRM_InstitutionID": "{{CustomObject[46].Field[594]}}",
    "Created_Date": "{{CustomObject[46].Field[595]}}",
    "Modified_Date": "{{CustomObject[46].Field[596]}}",
    "Owner": "{{CustomObject[46].Field[597]}}",
    "Created_By": "{{CustomObject[46].Field[598]}}",
    "Updated_By": "{{CustomObject[46].Field[599]}}",
    "ProductsandCampaigns": "{{CustomObject[46].Field[600]}}",
    "IM_CRM_Row_ID": "{{CustomObject[46].Field[584]}}",
    "IM_CRM_Contact_ID": "{{CustomObject[46].Field[586]}}"
}

institution_import_def = {
    "CompanyName": "{{CustomObject[45].Field[568]}}",
    "Address1": "{{CustomObject[45].Field[601]}}",
    "Address2": "{{CustomObject[45].Field[602]}}",
    "City": "{{CustomObject[45].Field[603]}}",
    "Zip_Postal": "{{CustomObject[45].Field[604]}}",
    "IM_CRM_Brick": "{{CustomObject[45].Field[569]}}",
    "Country": "{{CustomObject[45].Field[570]}}",
    "BusPhone": "{{CustomObject[45].Field[571]}}",
    "State_Prov": "{{CustomObject[45].Field[572]}}",
    "IM_CRM_Status": "{{CustomObject[45].Field[573]}}",
    "IM_CRM_Institution_Department": "{{CustomObject[45].Field[574]}}",
    "IM_CRM_Institution_ID": "{{CustomObject[45].Field[567]}}",
    "M_CRM_Institution_Territory": "{{CustomObject[45].Field[575]}}",
    "IM_CRM_Institution_Type": "{{CustomObject[45].Field[576]}}",
    "IM_CRM_Institution_Title": "{{CustomObject[45].Field[577]}}",
    "IM_CRM_Institution_Specialty": "{{CustomObject[45].Field[578]}}",
    "IM_CRM_Category": "{{CustomObject[45].Field[579]}}",
    "IM_CRM_Institution_Level": "{{CustomObject[45].Field[580]}}",
    "IM_CRM_Institution_Segmentation": "{{CustomObject[45].Field[581]}}",
    "IM_CRM_Institution_Area": "{{CustomObject[45].Field[582]}}",
    "IM_CRM_Row_ID": "{{CustomObject[45].Field[583]}}",
    "IM_CRM_Contact_ID": "{{CustomObject[45].Field[566]}}"
}

contact_import_def = {
    "C_Firstname": "{{Contact.Field(C_FirstName)}}",
    "C_Lastname": "{{Contact.Field(C_LastName)}}",
    "C_MobilePhone": "{{Contact.Field(C_MobilePhone)}}",
    "C_EmailAddress": "{{Contact.Field(C_EmailAddress)}}",
    "C_Salutation": "{{Contact.Field(C_Salutation)}}",
    "C_Country": "{{Contact.Field(C_Country)}}",
    "C_IM_CRM_Status1": "{{Contact.Field(C_IM_CRM_Status1)}}",
    "C_IM_CRM_Contact_ID1": "{{Contact.Field(C_IM_CRM_Contact_ID1)}}",
    "C_IM_CRM_Institution_ID1": "{{Contact.Field(C_IM_CRM_Institution_ID1)}}",
    "C_Company": "{{Contact.Field(C_Company)}}",
    "IM_CRM_GDPR": "{{Contact.Field(C_IM_CRM_GDPR1)}}",
    "C_IM_CRM_Gender1": "{{Contact.Field(C_IM_CRM_Gender1)}}",
    "C_IM_CRM_Target1": "{{Contact.Field(C_IM_CRM_Target1)}}",
    "C_IM_CRM_Function1": "{{Contact.Field(C_IM_CRM_Function1)}}",
    "C_IM_CRM_Person_Qualification1": "{{Contact.Field(C_IM_CRM_Person_Qualification1)}}",
    "C_IM_CRM_Person_Tendency1": "{{Contact.Field(C_IM_CRM_Person_Tendency1)}}",
    "C_IM_CRM_KAM_Person1": "{{Contact.Field(C_IM_CRM_KAM_Person1)}}",
    "IM_CRM_Product_Interest1": "{{Contact.Field(C_IM_CRM_Product_Interest1)}}",
    "IM_CRM_Segmentation1": "{{Contact.Field(C_IM_CRM_Segmentation1)}}",
    "IM_CRM_Person_Type1": "{{Contact.Field(C_IM_CRM_Person_Type1)}}",
    "C_Title": "{{Contact.Field(C_Title)}}",
    "C_Job_Role1": "{{Contact.Field(C_Job_Role1)}}",
    "IM_CRM_Doctor_in_Training1": "{{Contact.Field(C_IM_CRM_Doctor_in_Training1)}}",
    "C_B2B_Email_Consent1": "{{Contact.Field(C_B2B_Email_Consent1)}}",
    "C_B2B_Email_Consent_Date1": "{{Contact.Field(C_B2B_Email_Consent_Date1)}}",
    "C_B2B_Email_Consent_Source1": "{{Contact.Field(C_B2B_Email_Consent_Source1)}}",
    "C_IM_CRM_User_Name1": "{{Contact.Field(C_IM_CRM_User_Name1)}}",
    # security label
    "C_IM_CRM_Security_Label1": "{{Contact.Field(C_IM_CRM_Security_Label1)}}",
    "C_IM_CRM_Lead_Score1": "{{Contact.Field(C_IM_CRM_Lead_Score1)}}",
    "C_IM_CRM_Lead_Status1": "{{Contact.Field(C_IM_CRM_Lead_Status1)}}",
    # date last changed by CRM
    "C_LastModifiedByExtIntegrateSystem": "{{Contact.Field(C_LastModifiedByExtIntegrateSystem)}}"
}

contact_export_def = {
    "C_Firstname": "{{Contact.Field(C_FirstName)}}",
    "C_Lastname": "{{Contact.Field(C_LastName)}}",
    "C_MobilePhone": "{{Contact.Field(C_MobilePhone)}}",
    "C_EmailAddress": "{{Contact.Field(C_EmailAddress)}}",
    "C_Salutation": "{{Contact.Field(C_Salutation)}}",
    "C_Country": "{{Contact.Field(C_Country)}}",
    "C_Job_Role1": "{{Contact.Field(C_Job_Role1)}}",
    "C_Company": "{{Contact.Field(C_Company)}}",
    "C_Address1": "{{Contact.Field(C_Address1)}}",
    "C_State_Prov": "{{Contact.Field(C_State_Prov)}}",
    "C_City": "{{Contact.Field(C_City)}}",
    "C_Zip_Postal": "{{Contact.Field(C_Zip_Postal)}}",
    "C_IM_CRM_Contact_ID1": "{{Contact.Field(C_IM_CRM_Contact_ID1)}}",
    "C_B2B_Email_Consent1": "{{Contact.Field(C_B2B_Email_Consent1)}}",
    "C_B2B_Email_Consent_Date1": "{{Contact.Field(C_B2B_Email_Consent_Date1)}}",
    "C_B2B_Email_Consent_Source1": "{{Contact.Field(C_B2B_Email_Consent_Source1)}}",
    "C_IM_CRM_User_Name1": "{{Contact.Field(C_IM_CRM_User_Name1)}}",
    "C_IM_CRM_Security_Label1": "{{Contact.Field(C_IM_CRM_Security_Label1)}}",
    "C_IM_CRM_Lead_Score1": "{{Contact.Field(C_IM_CRM_Lead_Score1)}}",
    "C_IM_CRM_Lead_Status1": "{{Contact.Field(C_IM_CRM_Lead_Status1)}}"
}

contact_crm_id_export_def = {
    "id": eml.Contact.Id,
    "C_IM_CRM_Contact_ID1": "{{Contact.Field(C_IM_CRM_Contact_ID1)}}"
}


activity_export_def = {
    "EmailOpen": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        # mapped to contact
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "EmailClickthrough": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "EmailSend": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "FormSubmit": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "Subscribe": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "Unsubscribe": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "WebVisit": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "Duration": "{{Activity.Field(Duration)}}",
        "FirstPageViewUrl": "{{Activity.Field(FirstPageViewUrl)}}",
        "NumberOfPages": "{{Activity.Field(NumberOfPages)}}",
        "ReferrerUrl": "{{Activity.Field(ReferrerUrl)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "PageView": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "ReferrerUrl": "{{Activity.Field(ReferrerUrl)}}",
        "Url": "{{Activity.Field(Url)}}",
        "WebVisitId": "{{Activity.Field(WebVisitId)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    },
    "Bounceback": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "SmtpErrorCode": "{{Activity.Field(SmtpErrorCode)}}",
        "SmtpMessage": "{{Activity.Field(SmtpMessage)}}",
        "SmtpStatusCode": "{{Activity.Field(SmtpStatusCode)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
    }
}

activity_with_contact_export_def = {
    "EmailOpen": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        # mapped to contact
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "EmailClickthrough": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "EmailSend": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "EmailSendType": "{{Activity.Field(EmailSendType)}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "FormSubmit": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "Subscribe": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "Unsubscribe": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "WebVisit": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "Duration": "{{Activity.Field(Duration)}}",
        "FirstPageViewUrl": "{{Activity.Field(FirstPageViewUrl)}}",
        "NumberOfPages": "{{Activity.Field(NumberOfPages)}}",
        "ReferrerUrl": "{{Activity.Field(ReferrerUrl)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "PageView": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "VisitorExternalId": "{{Activity.Visitor.ExternalId}}",
        "VisitorId": "{{Activity.Visitor.Id}}",
        "ReferrerUrl": "{{Activity.Field(ReferrerUrl)}}",
        "Url": "{{Activity.Field(Url)}}",
        "WebVisitId": "{{Activity.Field(WebVisitId)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    },
    "Bounceback": {
        "ActivityDate": "{{Activity.CreatedAt}}",
        "ActivityId": "{{Activity.Id}}",
        "ActivityType": "{{Activity.Type}}",
        "AssetId": "{{Activity.Asset.Id}}",
        "AssetName": "{{Activity.Asset.Name}}",
        "AssetType": "{{Activity.Asset.Type}}",
        "CampaignId": "{{Activity.Campaign.Id}}",
        "ContactId": "{{Activity.Contact.Id}}",
        "ExternalId": "{{Activity.ExternalId}}",
        "SmtpErrorCode": "{{Activity.Field(SmtpErrorCode)}}",
        "SmtpMessage": "{{Activity.Field(SmtpMessage)}}",
        "SmtpStatusCode": "{{Activity.Field(SmtpStatusCode)}}",
        "C_IM_CRM_Contact_ID1": "{{Activity.Contact.Field(C_IM_CRM_Contact_ID1)}}",
        "C_DateModified": "{{Activity.Contact.Field(C_DateModified)}}",
    }
}
